package authserver

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"strings"
)

// Key prefixes for the KV store.
const (
	clientKeyPrefix  = "clients/"
	refreshKeyPrefix = "refresh/"
)

// persistedClient is the on-disk representation of a DCR client.
// Secrets are stored as bcrypt hashes — never plaintext.
type persistedClient struct {
	ClientID     string   `json:"client_id"`
	ClientName   string   `json:"client_name"`
	SecretHash   string   `json:"secret_hash"` // bcrypt hash of client_secret
	Scopes       []string `json:"scopes"`
	RedirectURIs []string `json:"redirect_uris"`
	Dynamic      bool     `json:"dynamic"`
}

// persistClient saves a DCR client to the KV store.
func (s *Server) persistClient(clientID, clientSecret, clientName string, scopes, redirectURIs []string) {
	if s.store == nil {
		return
	}

	// Hash the secret with SHA-256 for storage.
	// We use SHA-256 (not bcrypt) because client secrets are high-entropy random
	// strings generated by us — no brute-force risk. This keeps reads fast.
	hash := sha256Hash(clientSecret)

	pc := persistedClient{
		ClientID:     clientID,
		ClientName:   clientName,
		SecretHash:   hash,
		Scopes:       scopes,
		RedirectURIs: redirectURIs,
		Dynamic:      true,
	}

	data, err := json.Marshal(pc)
	if err != nil {
		s.logger.Warn("failed to marshal client for persistence", "client_id", clientID, "error", err)
		return
	}

	if err := s.store.Set(clientKeyPrefix+clientID, data); err != nil {
		s.logger.Warn("failed to persist client", "client_id", clientID, "error", err)
	}
}

// persistRefreshToken saves a refresh token → client_id mapping.
// The token itself is stored as a SHA-256 hash.
func (s *Server) persistRefreshToken(token, clientID string) {
	if s.store == nil {
		return
	}
	hash := sha256Hash(token)
	if err := s.store.Set(refreshKeyPrefix+hash, []byte(clientID)); err != nil {
		s.logger.Warn("failed to persist refresh token", "client_id", clientID, "error", err)
	}
}

// deleteRefreshToken removes a refresh token from the store.
func (s *Server) deleteRefreshToken(token string) {
	if s.store == nil {
		return
	}
	hash := sha256Hash(token)
	_ = s.store.Delete(refreshKeyPrefix + hash)
}

// loadPersistedState restores DCR clients and refresh tokens from the KV store.
// Errors are logged and ignored — the gateway starts clean if the store is corrupted.
func (s *Server) loadPersistedState() {
	if s.store == nil {
		return
	}

	// Load DCR clients.
	clientKeys, err := s.store.List(clientKeyPrefix)
	if err != nil {
		s.logger.Warn("failed to list persisted clients", "error", err)
		return
	}

	for _, key := range clientKeys {
		data, getErr := s.store.Get(key)
		if getErr != nil {
			continue
		}

		var pc persistedClient
		if getErr = json.Unmarshal(data, &pc); getErr != nil {
			s.logger.Warn("failed to unmarshal persisted client", "key", key, "error", getErr)
			continue
		}

		// Register the client. We store the hash as the "secret" — authentication
		// for persisted clients compares SHA-256(presented) against the stored hash.
		s.clients[pc.ClientID] = &ClientConfig{
			ClientID:      pc.ClientID,
			ClientSecret:  pc.SecretHash, // stored as hash
			AllowedScopes: pc.Scopes,
			Description:   pc.ClientName,
		}

		s.oauth.dynamics[pc.ClientID] = &dynamicClient{
			ClientID:     pc.ClientID,
			ClientName:   pc.ClientName,
			Scopes:       pc.Scopes,
			RedirectURIs: pc.RedirectURIs,
		}

		s.logger.Info("restored persisted client", "client_id", pc.ClientID, "name", pc.ClientName)
	}

	// Load refresh tokens.
	refreshKeys, err := s.store.List(refreshKeyPrefix)
	if err != nil {
		s.logger.Warn("failed to list persisted refresh tokens", "error", err)
		return
	}

	for _, key := range refreshKeys {
		data, err := s.store.Get(key)
		if err != nil {
			continue
		}
		clientID := string(data)
		// The key is "refresh/{hash}" — extract the hash part.
		hash := strings.TrimPrefix(key, refreshKeyPrefix)
		s.oauth.refresh[hash] = &refreshToken{clientID: clientID}
	}

	if len(clientKeys) > 0 || len(refreshKeys) > 0 {
		s.logger.Info("restored persisted state",
			"clients", len(clientKeys),
			"refresh_tokens", len(refreshKeys),
		)
	}
}

func sha256Hash(s string) string {
	h := sha256.Sum256([]byte(s))
	return hex.EncodeToString(h[:])
}
