package authserver

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"strings"
	"time"
)

// Key prefixes for the KV store.
const (
	clientKeyPrefix  = "clients/"
	refreshKeyPrefix = "refresh/"
)

// persistedClient is the on-disk representation of a DCR client.
// Secrets are stored as SHA-256 hashes — never plaintext.
type persistedClient struct {
	ClientID     string   `json:"client_id"`
	ClientName   string   `json:"client_name"`
	PrismID      string   `json:"prism_id"`    // Prism-generated stable UUID
	Label        string   `json:"label"`       // Operator-assigned label from consent page
	SecretHash   string   `json:"secret_hash"` // SHA-256 hash of client_secret
	Scopes       []string `json:"scopes"`
	RedirectURIs []string `json:"redirect_uris"`
	Dynamic      bool     `json:"dynamic"`
	CreatedAt    string   `json:"created_at,omitempty"`   // RFC 3339
	LastUsedAt   string   `json:"last_used_at,omitempty"` // RFC 3339, updated on refresh
}

// persistClient saves a DCR client to the KV store.
func (s *Server) persistClient(clientID, clientSecret, clientName string, scopes, redirectURIs []string) {
	if s.store == nil {
		return
	}

	// Hash the secret with SHA-256 for storage.
	// We use SHA-256 (not bcrypt) because client secrets are high-entropy random
	// strings generated by us — no brute-force risk. This keeps reads fast.
	hash := sha256Hash(clientSecret)

	pc := persistedClient{
		ClientID:     clientID,
		ClientName:   clientName,
		SecretHash:   hash,
		Scopes:       scopes,
		RedirectURIs: redirectURIs,
		Dynamic:      true,
		CreatedAt:    time.Now().UTC().Format(time.RFC3339),
	}

	data, err := json.Marshal(pc)
	if err != nil {
		s.logger.Warn("failed to marshal client for persistence", "client_id", clientID, "error", err)
		return
	}

	if err := s.store.Set(clientKeyPrefix+clientID, data); err != nil {
		s.logger.Warn("failed to persist client", "client_id", clientID, "error", err)
	}
}

// updateClientIdentity sets the PrismID and Label on a persisted client.
func (s *Server) updateClientIdentity(clientID, prismID, label string) {
	if s.store == nil {
		return
	}
	data, getErr := s.store.Get(clientKeyPrefix + clientID)
	if getErr != nil {
		return
	}
	var pc persistedClient
	if getErr = json.Unmarshal(data, &pc); getErr != nil {
		return
	}
	pc.PrismID = prismID
	pc.Label = label
	updated, _ := json.Marshal(pc)
	if err := s.store.Set(clientKeyPrefix+clientID, updated); err != nil {
		s.logger.Warn("failed to persist client identity", "client_id", clientID, "error", err)
	}
}

// updateLastUsed updates the LastUsedAt timestamp on a dynamic client.
func (s *Server) updateLastUsed(clientID string) {
	nowStr := time.Now().UTC().Format(time.RFC3339)

	// Update in-memory.
	s.oauth.mu.Lock()
	if dc, ok := s.oauth.dynamics[clientID]; ok {
		dc.LastUsedAt = nowStr
	}
	s.oauth.mu.Unlock()

	// Update in KV store.
	if s.store == nil {
		return
	}
	data, getErr := s.store.Get(clientKeyPrefix + clientID)
	if getErr != nil {
		return
	}
	var pc persistedClient
	if getErr = json.Unmarshal(data, &pc); getErr != nil {
		return
	}
	pc.LastUsedAt = nowStr
	updated, _ := json.Marshal(pc)
	_ = s.store.Set(clientKeyPrefix+clientID, updated)
}

// persistedRefreshToken is the on-disk shape: client_id + issued_at so we
// can enforce a maximum lifetime across restarts and rotations.
type persistedRefreshToken struct {
	ClientID string    `json:"client_id"`
	IssuedAt time.Time `json:"issued_at"`
}

// persistRefreshToken saves a refresh token → (client_id, issued_at) mapping.
// The token itself is stored as a SHA-256 hash.
func (s *Server) persistRefreshToken(token, clientID string, issuedAt time.Time) {
	if s.store == nil {
		return
	}
	hash := sha256Hash(token)
	data, err := json.Marshal(persistedRefreshToken{ClientID: clientID, IssuedAt: issuedAt})
	if err != nil {
		s.logger.Warn("failed to marshal refresh token", "client_id", clientID, "error", err)
		return
	}
	if err := s.store.Set(refreshKeyPrefix+hash, data); err != nil {
		s.logger.Warn("failed to persist refresh token", "client_id", clientID, "error", err)
	}
}

// deleteRefreshToken removes a refresh token from the store.
func (s *Server) deleteRefreshToken(token string) {
	if s.store == nil {
		return
	}
	hash := sha256Hash(token)
	_ = s.store.Delete(refreshKeyPrefix + hash)
}

// loadPersistedState restores DCR clients and refresh tokens from the KV store.
// Errors are logged and ignored — the gateway starts clean if the store is corrupted.
func (s *Server) loadPersistedState() {
	if s.store == nil {
		return
	}
	clientCount := s.loadPersistedClients()
	refreshCount := s.loadPersistedRefreshTokens()

	if clientCount > 0 || refreshCount > 0 {
		s.logger.Info("restored persisted state",
			"clients", clientCount,
			"refresh_tokens", refreshCount,
		)
	}

	// Restore runtime-modified default scopes (if any).
	s.loadPersistedDefaults()
}

// loadPersistedClients restores DCR client records from KV.
func (s *Server) loadPersistedClients() int {
	clientKeys, err := s.store.List(clientKeyPrefix)
	if err != nil {
		s.logger.Warn("failed to list persisted clients", "error", err)
		return 0
	}
	for _, key := range clientKeys {
		s.loadOnePersistedClient(key)
	}
	return len(clientKeys)
}

func (s *Server) loadOnePersistedClient(key string) {
	data, err := s.store.Get(key)
	if err != nil {
		return
	}
	var pc persistedClient
	if err := json.Unmarshal(data, &pc); err != nil {
		s.logger.Warn("failed to unmarshal persisted client", "key", key, "error", err)
		return
	}
	// In-memory ClientSecret is always a SHA-256 hash.
	s.clients[pc.ClientID] = &ClientConfig{
		ClientID:      pc.ClientID,
		ClientSecret:  pc.SecretHash,
		AllowedScopes: pc.Scopes,
		Description:   pc.ClientName,
	}
	s.oauth.dynamics[pc.ClientID] = &dynamicClient{
		ClientID:     pc.ClientID,
		ClientName:   pc.ClientName,
		Scopes:       pc.Scopes,
		RedirectURIs: pc.RedirectURIs,
		PrismID:      pc.PrismID,
		Label:        pc.Label,
		CreatedAt:    pc.CreatedAt,
		LastUsedAt:   pc.LastUsedAt,
	}
	displayName := pc.Label
	if displayName == "" {
		displayName = pc.ClientName
	}
	s.logger.Info("restored persisted client",
		"client_id", pc.ClientID,
		"name", displayName,
		"prism_id", pc.PrismID,
	)
}

// loadPersistedRefreshTokens restores refresh-token records from KV.
// Tokens past the max age are dropped on load.
func (s *Server) loadPersistedRefreshTokens() int {
	refreshKeys, err := s.store.List(refreshKeyPrefix)
	if err != nil {
		s.logger.Warn("failed to list persisted refresh tokens", "error", err)
		return 0
	}
	loaded := 0
	for _, key := range refreshKeys {
		if s.loadOnePersistedRefreshToken(key) {
			loaded++
		}
	}
	return loaded
}

func (s *Server) loadOnePersistedRefreshToken(key string) bool {
	data, err := s.store.Get(key)
	if err != nil {
		return false
	}
	// New format is JSON {client_id, issued_at}; legacy entries are
	// raw client_id bytes — read them but leave issuedAt zero so the
	// refresh handler rejects them and forces a re-auth.
	var stored persistedRefreshToken
	if jsonErr := json.Unmarshal(data, &stored); jsonErr != nil || stored.ClientID == "" {
		stored = persistedRefreshToken{ClientID: string(data)}
	}
	// Drop on load if already past max age.
	if !stored.IssuedAt.IsZero() && time.Since(stored.IssuedAt) > refreshTokenMaxAge {
		_ = s.store.Delete(key)
		return false
	}
	hash := strings.TrimPrefix(key, refreshKeyPrefix)
	s.oauth.refresh[hash] = &refreshToken{
		clientID: stored.ClientID,
		issuedAt: stored.IssuedAt,
	}
	return true
}

func sha256Hash(s string) string {
	h := sha256.Sum256([]byte(s))
	return hex.EncodeToString(h[:])
}

// isHexSHA256 reports whether s looks like an already-hashed SHA-256 hex
// string (64 lowercase hex chars). Used to decide whether a static client
// secret in the config file is plaintext (we'll hash it) or a pre-computed
// hash (we'll use it directly).
func isHexSHA256(s string) bool {
	if len(s) != 64 {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= '0' && c <= '9', c >= 'a' && c <= 'f':
			// ok
		default:
			return false
		}
	}
	return true
}

// normalizeClientSecret returns the form that should be stored in memory and
// compared against the SHA-256(presented) value at authentication time. A
// pre-hashed config value is used as-is; anything else is hashed on the way
// in so the in-memory ClientSecret is never plaintext.
func normalizeClientSecret(s string) string {
	if isHexSHA256(s) {
		return s
	}
	return sha256Hash(s)
}
